/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BackyardMonsters.electric.monsterloo;

public class App {

    public static void main(String[] args) {
        new Server(1337);
    }
}
