/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BackyardMonsters.electric.monsterloo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

}
